In [1]:
import numpy as np
from sklearn.decomposition import NMF
import pandas as pd

In [2]:
# movie, ratings by users
data = [
    [5, 4, 1, 1, 3],
    [3, 2, 1, 3, 1],
    [3, 3, 3, 3, 5],
    [1, 1, 5, 4, 4],
]
columns = ['Titanic', 'Tiffany', 'Terminator', 'Star Trek', 'Star Wars'] #movies
index = ['Ada', 'Bob', 'Steve', 'Margaret'] #users

#need a dataframe for this
R = pd.DataFrame(data, index=index, columns=columns).values
R_df = pd.DataFrame(data, index=index, columns=columns)
R_df

Titanic  Tiffany  Terminator  Star Trek  Star Wars
Ada             5        4           1          1          3
Bob             3        2           1          3          1
Steve           3        3           3          3          5
Margaret        1        1           5          4          4

In [3]:
#create a model and set the hyperparameters
# model assumes R ~ PQ'
model = NMF(n_components=2, init='random', random_state=10)

model.fit(R)

Q = model.components_  # movie-genre matrix

P = model.transform(R)  # user-genre matrix

print(model.reconstruction_err_) #reconstruction error

2.319822011025


In [4]:
nR = np.dot(P, Q)
print(nR) ## The reconstructed matrix!

[[4.98574011 3.98089613 0.69817861 1.52507923 2.84430572]
 [2.61580597 2.15486368 1.23495386 1.51110529 2.19736573]
 [3.35829506 2.89944467 3.32824145 3.36641177 4.23566511]
 [0.85105386 1.03300314 4.75334969 4.0532461  4.24705685]]


In [5]:
# predict the hidden features for a new data point
query = [[1, 2, 5, 4, 5]]
#in this case, a new user providing ratings for the 5 movies.
print(model.transform(query))

[[2.68231475 0.45631224]]
