### NumPy Solution to: 

- "Pen and Paper" exercise:

https://krspiced.pythonanywhere.com/_downloads/e4a79fdee9c83f9e1ac07b61a28e8bc4/ANN_Exercise.pdf

In [1]:
import numpy as np

In [2]:
# our input data from the pdf exerise, x1 and x2
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0], 
    [1, 1]
])

In [3]:
# the third column is the byas
X = np.hstack((X, np.ones(shape=(4,1))))

In [4]:
X

array([[0., 0., 1.],
       [0., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

In [5]:
X.shape

(4, 3)

In [6]:
weights_AND = np.array([1, 1, 0])

In [7]:
weights_AND

array([1, 1, 0])

In [8]:
weights_AND.shape

(3,)

In [9]:
def step(x) -> bool:
    
    """python implementation of the step function.
       - 1 (or TRUE / ON) if greater than 1.
       - 0 (or FALSE /OFF) if not.
       """
    
#     if x > 1:
#         return True
#     else:
#         return False

    return x > 1

In [10]:
solution_step = step(np.dot(X, weights_AND)) #solution to the AND problem

In [11]:
solution_step.shape

(4,)

How a Neural Network calculates:
- Multiply input and weights
- (add bias)
- activate!

In [12]:
weights_OR = np.array([1.1, 1.1, 0])

In [13]:
step(np.dot(X, weights_OR)) #this is what a single neuron does!
#solution to the OR problem

array([False,  True,  True,  True])

The XOR problem:
- a little more challenging because we have to make sure the output from the first "layer" of neurons is then reassembled back into a matrix to be used as the input to the final neuron / layer.

In [14]:
weights_XOR_1 = np.array([1.1, -1.1, 0]) #x1 AND NOT x2
weights_XOR_2 = np.array([-1.1, 1.1, 0]) #x2 AND NOT x1
weights_XOR_3 = weights_OR #result A OR result B

In [15]:
neuron1 = step(np.dot(X, weights_XOR_1))
neuron2 = step(np.dot(X, weights_XOR_2))

In [16]:
hidden_output = np.vstack([neuron1, neuron2, np.ones(4)]).transpose()
#an intermediate layer of neurons
#sometimes you need to transpose to make sure the shapes are lined up.

In [17]:
hidden_output.shape

(4, 3)

In [18]:
step(np.dot(hidden_output, weights_XOR_3)) #solution to XOR

array([False,  True,  True, False])

## Implement a feed-forward-network

In [2]:
from sklearn.datasets import make_moons
import random 
random.seed=(666)

X, y = make_moons(n_samples=50, noise=0.2, random_state=42)

In [3]:
X

array([[-0.15856989,  0.98480618],
       [ 1.10900374, -0.62160223],
       [ 0.39641523,  0.20740869],
       [ 1.79239122,  0.07511293],
       [-0.84739307,  0.71154296],
       [ 1.90209657,  0.67432213],
       [ 0.0731551 ,  0.09079042],
       [-0.43566685,  0.29122072],
       [ 0.42577731, -0.22851359],
       [-0.64418143,  0.24144478],
       [ 0.11289285,  1.00510013],
       [ 0.96066405,  0.63183812],
       [ 1.46814927, -0.28580296],
       [ 0.5192833 ,  0.94984582],
       [ 0.73327397,  0.17310931],
       [ 0.33197143,  0.43375035],
       [ 1.62726102, -0.54736954],
       [ 2.01908805,  0.37804882],
       [ 2.00824323,  0.36058988],
       [-0.56195047,  0.90148197],
       [ 0.67647169,  0.69909987],
       [-0.30999892,  1.2113287 ],
       [-0.90842298, -0.33685748],
       [ 0.68268561, -0.44010332],
       [ 0.38645217, -0.05988231],
       [ 0.84405962, -0.16877927],
       [ 1.76324657, -0.30187296],
       [ 0.06417199,  0.2184967 ],
       [ 1.02670564,

In [4]:
y

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1])

In [5]:
X.shape, y.shape

((50, 2), (50,))

In [54]:
#import seaborn as sns

In [55]:
#X = np.hstack([X, np.ones((X.shape[0], 1))])
#X

In [6]:
def add_bias(X):
    return np.hstack([X, np.ones((X.shape[0], 1))])

In [7]:
X = add_bias(X)
X

array([[-0.15856989,  0.98480618,  1.        ],
       [ 1.10900374, -0.62160223,  1.        ],
       [ 0.39641523,  0.20740869,  1.        ],
       [ 1.79239122,  0.07511293,  1.        ],
       [-0.84739307,  0.71154296,  1.        ],
       [ 1.90209657,  0.67432213,  1.        ],
       [ 0.0731551 ,  0.09079042,  1.        ],
       [-0.43566685,  0.29122072,  1.        ],
       [ 0.42577731, -0.22851359,  1.        ],
       [-0.64418143,  0.24144478,  1.        ],
       [ 0.11289285,  1.00510013,  1.        ],
       [ 0.96066405,  0.63183812,  1.        ],
       [ 1.46814927, -0.28580296,  1.        ],
       [ 0.5192833 ,  0.94984582,  1.        ],
       [ 0.73327397,  0.17310931,  1.        ],
       [ 0.33197143,  0.43375035,  1.        ],
       [ 1.62726102, -0.54736954,  1.        ],
       [ 2.01908805,  0.37804882,  1.        ],
       [ 2.00824323,  0.36058988,  1.        ],
       [-0.56195047,  0.90148197,  1.        ],
       [ 0.67647169,  0.69909987,  1.   

In [8]:
X.shape

(50, 3)

In [9]:
# activation by a sigmoid
def sigmoid(matrix):
    return (1/(1+np.exp(-matrix)))

In [10]:
# sanity check
a = np.array([-10.0, -1.0, 0.0, 1.0, 10.0])
expected = np.array([0.0, 0.27, 0.5, 0.73, 1.0])
assert np.all(sigmoid(a).round(2) == expected)

In [11]:
# weight_1
w_1 = np.random.rand(3,2)
w_1.shape

(3, 2)

In [12]:
# weight_2
w_2 = np.random.rand(3,1)
w_2.shape

(3, 1)

In [13]:
def add_bias_check_dimension(matrix,first_weight):
    if matrix.shape[1] == first_weight.shape[0]:
        return matrix
    else:
        return np.hstack([matrix, np.ones((matrix.shape[0], 1))])

In [14]:
def feed_forward(X, weights):

    """
    1. Multiply the input matrix X
       with the weights of the first layer.

    2. Apply the sigmoid function on the result.

    3. Append an extra column of ones to the result (i.e. the bias).

    4. Multiply the output of the previous step
       with the weights of the second (i.e. outer) layer.

    5. Apply the sigmoid function on the result.

    6. Return all intermediate results (i.e. anything that is outputted
       by an activation function).
    """
    
    
    output = [X]
    for weight in weights:
        
        # step0
        X1 = add_bias_check_dimension(output[-1], weight)
        
        # step1
        res_1 = np.dot(X1, weight)
    
        # step2
        output_new = sigmoid(res_1)
        
        output.append(output_new)
    
    
    
    out = output[1:]
    return out

In [15]:
feed_forward(X, [w_1,w_2])

[array([[0.70240657, 0.7356057 ],
        [0.60294744, 0.6774659 ],
        [0.65459854, 0.7080894 ],
        [0.67624207, 0.70830487],
        [0.66601922, 0.72282009],
        [0.72338194, 0.73163451],
        [0.63745958, 0.70222952],
        [0.64178477, 0.70815534],
        [0.61942379, 0.69081847],
        [0.63270288, 0.7053883 ],
        [0.70973206, 0.73733999],
        [0.70031904, 0.72655925],
        [0.63979866, 0.69266362],
        [0.71431397, 0.73678313],
        [0.65969458, 0.70804823],
        [0.67112092, 0.71664258],
        [0.62193994, 0.68264304],
        [0.70430518, 0.72089378],
        [0.70277443, 0.72018573],
        [0.68727202, 0.7310359 ],
        [0.69917745, 0.72803504],
        [0.71581535, 0.74334034],
        [0.57701964, 0.68100565],
        [0.60785743, 0.68321963],
        [0.6325315 , 0.69745602],
        [0.63451384, 0.69489804],
        [0.6454922 , 0.69319087],
        [0.6476914 , 0.70723725],
        [0.60521844, 0.67922298],
        [0.697

In [16]:
# sanity check
out1, out2 = feed_forward(X, [w_1, w_2])
assert out1.shape == (50, 2)
assert out2.shape == (50, 1)

Xref = np.array([[1.0, 2.0, 1.0]])
whidden = np.array([[1.0, 2.0, 0.0],
                 [-1.0, -2.0, 0.0]
                    ]).T
wout = np.array([[1.0, -1.0, 0.5]]).T

out1, out2 = feed_forward(Xref, [whidden, wout])
assert np.all(out1.round(2) == np.array([[0.99, 0.01]]))
assert np.all(out2.round(2) == np.array([[0.82]]))