### NumPy Solution to: 

- "Pen and Paper" exercise:

https://krspiced.pythonanywhere.com/_downloads/e4a79fdee9c83f9e1ac07b61a28e8bc4/ANN_Exercise.pdf

In [55]:
import numpy as np

In [56]:
# our input data from the pdf exerise, x1 and x2
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0], 
    [1, 1]
])

In [57]:
X = np.hstack((X, np.ones(shape=(4,1))))
#manually add on the bias

In [58]:
X

array([[0., 0., 1.],
       [0., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

In [59]:
weights_AND = np.array([1, 1, 0])

In [60]:
weights_AND

array([1, 1, 0])

In [61]:
def step(x) -> bool:
    
    """python implementation of the step function.
       - 1 (or TRUE / ON) if greater than 1.
       - 0 (or FALSE /OFF) if not.
       """
    
#     if x > 1:
#         return True
#     else:
#         return False

    return x > 1

In [62]:
step(np.dot(X, weights_AND)) #solution to the AND problem

array([False, False, False,  True])

How a Neural Network calculates:
- Multiply input and weights
- (add bias)
- activate!

In [63]:
weights_OR = np.array([1.1, 1.1, 0])

In [64]:
step(np.dot(X, weights_OR)) #this is what a single neuron does!
#solution to the OR problem

array([False,  True,  True,  True])

The XOR problem:
- a little more challenging because we have to make sure the output from the first "layer" of neurons is then reassembled back into a matrix to be used as the input to the final neuron / layer.

In [65]:
weights_XOR_1 = np.array([1.1, -1.1, 0]) #x1 AND NOT x2
weights_XOR_2 = np.array([-1.1, 1.1, 0]) #x2 AND NOT x1
weights_XOR_3 = weights_OR #result A OR result B

In [66]:
neuron1 = step(np.dot(X, weights_XOR_1))
neuron2 = step(np.dot(X, weights_XOR_2))

In [67]:
hidden_output = np.vstack([neuron1, neuron2, np.ones(4)]).transpose()
#an intermediate layer of neurons
#sometimes you need to transpose to make sure the shapes are lined up.

In [68]:
step(np.dot(hidden_output, weights_XOR_3)) #solution to XOR

array([False,  True,  True, False])